# Generated by Django 3.2.4 on 2021-06-22 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('rutRegistro', models.IntegerField(max_length=8, primary_key=True, serialize=False, verbose_name='Rut')),
                ('dvRegistro', models.CharField(max_length=1, verbose_name='Dígito Verificador')),
                ('nombreRegistro', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellidoRegistro', models.CharField(max_length=50, verbose_name='Apellido')),
                ('fechaNacimientoRegistro', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('numContactoRegistro', models.IntegerField(max_length=8, verbose_name='Número de Contacto')),
                ('correoRegistro', models.CharField(max_length=100, verbose_name='Correo Electrónico')),
                ('nombreUsuarioRegistro', models.CharField(max_length=50, verbose_name='Nombre de Usuario')),
                ('contraseñaRegistro', models.CharField(max_length=10, verbose_name='Contraseña')),
                ('repetirContraseñaRegistro', models.CharField(max_length=10, verbose_name='Repetir Contraseña')),
            ],
        ),
    ]
