# Generated by Django 3.2.4 on 2021-06-22 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='numContactoRegistro',
            field=models.IntegerField(verbose_name='Número de Contacto'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='rutRegistro',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Rut'),
        ),
    ]
