# Generated by Django 3.2.4 on 2021-06-22 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sams', '0002_auto_20210621_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='numContactoRegistro',
            field=models.IntegerField(verbose_name='Número de Contacto (+569)'),
        ),
    ]
