# Generated by Django 3.2.4 on 2021-06-22 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sams', '0003_alter_registro_numcontactoregistro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro',
            old_name='apellidoRegistro',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='contraseñaRegistro',
            new_name='contraseña',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='correoRegistro',
            new_name='correo',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='dvRegistro',
            new_name='dv',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='fechaNacimientoRegistro',
            new_name='fecha_nacimiento',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='nombreRegistro',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='nombreUsuarioRegistro',
            new_name='nombre_usuario',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='numContactoRegistro',
            new_name='num_contacto',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='repetirContraseñaRegistro',
            new_name='repetir_contraseña',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='rutRegistro',
            new_name='rut',
        ),
    ]
