# Generated by Django 3.2.4 on 2021-06-22 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sams', '0004_auto_20210622_0246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro',
            old_name='apellido',
            new_name='apellidoRegistro',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='contraseña',
            new_name='contraseñaRegistro',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='correo',
            new_name='correoRegistro',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='dv',
            new_name='dvRegistro',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='fecha_nacimiento',
            new_name='fechaNacimientoRegistro',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='nombre',
            new_name='nombreRegistro',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='nombre_usuario',
            new_name='nombreUsuarioRegistro',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='num_contacto',
            new_name='numContactoRegistro',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='repetir_contraseña',
            new_name='repetirContraseñaRegistro',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='rut',
            new_name='rutRegistro',
        ),
    ]
